// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpZBNfPJYW24XVvwDlfKvF7n-NKytJ8Fs',
    appId: '1:952316582816:web:688c87c6c79822dbaee2c5',
    messagingSenderId: '952316582816',
    projectId: 'home-ring-b24e4',
    authDomain: 'home-ring-b24e4.firebaseapp.com',
    databaseURL: 'https://home-ring-b24e4-default-rtdb.firebaseio.com',
    storageBucket: 'home-ring-b24e4.firebasestorage.app',
    measurementId: 'G-5G17KBD545',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA53fIrxKHiJVlu4l-n4xQxWeyeRUDQZQ0',
    appId: '1:952316582816:android:814c43703112e3eaaee2c5',
    messagingSenderId: '952316582816',
    projectId: 'home-ring-b24e4',
    databaseURL: 'https://home-ring-b24e4-default-rtdb.firebaseio.com',
    storageBucket: 'home-ring-b24e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdZ-T-dfHr93P60vUHhYtV9HKqXIDLuX0',
    appId: '1:952316582816:ios:578b6d31f43888ceaee2c5',
    messagingSenderId: '952316582816',
    projectId: 'home-ring-b24e4',
    databaseURL: 'https://home-ring-b24e4-default-rtdb.firebaseio.com',
    storageBucket: 'home-ring-b24e4.firebasestorage.app',
    iosClientId: '952316582816-9j4a98fk0qq7jk06alua4nq7v6k1nitl.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeRing',
  );
}
